server:
  port: 22100
spring:
  application:
    name: xc-service-base-filesystem
#mongo配置
  data:
    mongodb:
      uri: mongodb://192.168.170.128:27017/
      database: xc_fs
#SpringMVC上传文件配置
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 1MB
      # 最大支持请求大小
      max-request-size: 30MB
#fastdfs配置
fdfs:
  so-timeout: 1501     # 超时时间
  connect-timeout: 601   # 连接超时时间
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.200.128:22122
#    - 192.168.170.128:22122
#    - 192.168.0.105:22122
  pool:
    max-total: 153
    max-wait-millis: 102

