server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://192.168.170.128:27017/
      database: xc_cms
  rabbitmq:
    host: 192.168.170.128
    port: 5672
    username: guest
    password: guest
    virtual-host: /